### ISSUE TITLE
Can't set lobby size to 16

### ISSUE THREAD

**Issue by kiwec** [ThePooN/bancho.js#11]
Lobby size is limited to 15, when it should be limited to 16.

https://github.com/ThePooN/bancho.js/blob/ab3f14fb76e4ecb8062efca537c83befe3e9c6e1/lib/Multiplayer/BanchoLobby.js#L580

An exception is thrown but bancho accepts the command just fine when you type it in manually. Sorry for making an issue on github for a 1-character fix, discord doesn't like my IP :(

**Comment by ThePooN** [comment]
Well it's not limited to 16... but that conditional is very wrong either way.

I remember coding most of bancho.js's multiplayer support in a single night and there it shows.

**Comment by ThePooN** [comment]
Fixed in 0.10.0-rc.6
